import { BillingFrequency } from '../../../subscriptions/domain/enums/billing-frequency.enum';
import { TemplateCategory } from '../../domain/enums/template-category.enum';
import { TemplateOwnership } from '../../domain/enums/template-ownership.enum';

export interface SeedTemplate {
  name: string;
  description: string;
  iconUrl: string;
  serviceUrl: string;
  defaultAmount: number;
  defaultFrequency: BillingFrequency;
  category: TemplateCategory;
  ownership: TemplateOwnership;
  userId: null;
}

export const GLOBAL_TEMPLATES: SeedTemplate[] = [
  // ── STREAMING (8) ───────────────────────────────────────────────────────────
  {
    name: 'Netflix',
    description: 'Video streaming service with movies and TV shows',
    iconUrl: 'https://logo.clearbit.com/netflix.com',
    serviceUrl: 'https://netflix.com',
    defaultAmount: 15.49,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.STREAMING,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Disney+',
    description:
      'Streaming service for Disney, Marvel, Star Wars and National Geographic',
    iconUrl: 'https://logo.clearbit.com/disneyplus.com',
    serviceUrl: 'https://disneyplus.com',
    defaultAmount: 13.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.STREAMING,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'HBO Max',
    description:
      'Streaming platform with HBO originals, Warner Bros. films and more',
    iconUrl: 'https://logo.clearbit.com/max.com',
    serviceUrl: 'https://max.com',
    defaultAmount: 15.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.STREAMING,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Amazon Prime Video',
    description: 'Video streaming service included with Amazon Prime',
    iconUrl: 'https://logo.clearbit.com/primevideo.com',
    serviceUrl: 'https://primevideo.com',
    defaultAmount: 8.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.STREAMING,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Hulu',
    description: 'Live and on-demand TV and movie streaming service',
    iconUrl: 'https://logo.clearbit.com/hulu.com',
    serviceUrl: 'https://hulu.com',
    defaultAmount: 7.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.STREAMING,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Apple TV+',
    description: 'Apple original series, movies, and documentaries',
    iconUrl: 'https://logo.clearbit.com/apple.com',
    serviceUrl: 'https://tv.apple.com',
    defaultAmount: 9.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.STREAMING,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Paramount+',
    description:
      'Streaming service with CBS, Nickelodeon, MTV, BET and Paramount films',
    iconUrl: 'https://logo.clearbit.com/paramountplus.com',
    serviceUrl: 'https://paramountplus.com',
    defaultAmount: 5.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.STREAMING,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Peacock',
    description:
      'NBCUniversal streaming service with live sports, news and entertainment',
    iconUrl: 'https://logo.clearbit.com/peacocktv.com',
    serviceUrl: 'https://peacocktv.com',
    defaultAmount: 5.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.STREAMING,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },

  // ── MUSIC (6) ────────────────────────────────────────────────────────────────
  {
    name: 'Spotify',
    description: 'Music, podcast and audiobook streaming platform',
    iconUrl: 'https://logo.clearbit.com/spotify.com',
    serviceUrl: 'https://spotify.com',
    defaultAmount: 10.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.MUSIC,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Apple Music',
    description: 'Music streaming service with 100M+ songs',
    iconUrl: 'https://logo.clearbit.com/apple.com',
    serviceUrl: 'https://music.apple.com',
    defaultAmount: 10.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.MUSIC,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'YouTube Music',
    description: 'Music streaming service from Google with YouTube integration',
    iconUrl: 'https://logo.clearbit.com/music.youtube.com',
    serviceUrl: 'https://music.youtube.com',
    defaultAmount: 10.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.MUSIC,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Amazon Music Unlimited',
    description: 'Full on-demand music streaming service from Amazon',
    iconUrl: 'https://logo.clearbit.com/amazon.com',
    serviceUrl: 'https://amazon.com/music/unlimited',
    defaultAmount: 9.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.MUSIC,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Tidal',
    description: 'High-fidelity music and video streaming service',
    iconUrl: 'https://logo.clearbit.com/tidal.com',
    serviceUrl: 'https://tidal.com',
    defaultAmount: 10.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.MUSIC,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Deezer',
    description: 'Music streaming service with 90M+ tracks and podcasts',
    iconUrl: 'https://logo.clearbit.com/deezer.com',
    serviceUrl: 'https://deezer.com',
    defaultAmount: 10.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.MUSIC,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },

  // ── GAMING (6) ───────────────────────────────────────────────────────────────
  {
    name: 'Xbox Game Pass Ultimate',
    description: 'Access to 100+ Xbox and PC games plus Xbox Live Gold',
    iconUrl: 'https://logo.clearbit.com/xbox.com',
    serviceUrl: 'https://xbox.com/game-pass',
    defaultAmount: 14.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.GAMING,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'PlayStation Plus',
    description: 'PlayStation online multiplayer and free monthly games',
    iconUrl: 'https://logo.clearbit.com/playstation.com',
    serviceUrl: 'https://playstation.com/ps-plus',
    defaultAmount: 59.99,
    defaultFrequency: BillingFrequency.ANNUAL,
    category: TemplateCategory.GAMING,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Nintendo Switch Online',
    description:
      'Online play, cloud saves and classic NES/SNES games for Nintendo Switch',
    iconUrl: 'https://logo.clearbit.com/nintendo.com',
    serviceUrl: 'https://nintendo.com/switch/online',
    defaultAmount: 19.99,
    defaultFrequency: BillingFrequency.ANNUAL,
    category: TemplateCategory.GAMING,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'EA Play',
    description: "Access to EA's library of top games and early trials",
    iconUrl: 'https://logo.clearbit.com/ea.com',
    serviceUrl: 'https://ea.com/ea-play',
    defaultAmount: 4.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.GAMING,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Ubisoft+',
    description: "Access to Ubisoft's full game catalog and new releases",
    iconUrl: 'https://logo.clearbit.com/ubisoft.com',
    serviceUrl: 'https://ubisoft.com/ubisoft-plus',
    defaultAmount: 17.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.GAMING,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Humble Bundle Monthly',
    description: 'Monthly bundle of DRM-free games at a discounted price',
    iconUrl: 'https://logo.clearbit.com/humblebundle.com',
    serviceUrl: 'https://humblebundle.com/monthly',
    defaultAmount: 12.0,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.GAMING,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },

  // ── CLOUD STORAGE (6) ────────────────────────────────────────────────────────
  {
    name: 'Google One',
    description: 'Google cloud storage for Drive, Gmail and Photos',
    iconUrl: 'https://logo.clearbit.com/one.google.com',
    serviceUrl: 'https://one.google.com',
    defaultAmount: 2.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.CLOUD_STORAGE,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'iCloud+',
    description: 'Apple iCloud storage and privacy features',
    iconUrl: 'https://logo.clearbit.com/apple.com',
    serviceUrl: 'https://apple.com/icloud',
    defaultAmount: 2.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.CLOUD_STORAGE,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Dropbox Plus',
    description: 'Cloud storage and file synchronization service',
    iconUrl: 'https://logo.clearbit.com/dropbox.com',
    serviceUrl: 'https://dropbox.com',
    defaultAmount: 11.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.CLOUD_STORAGE,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'OneDrive',
    description: 'Microsoft cloud storage integrated with Office 365',
    iconUrl: 'https://logo.clearbit.com/microsoft.com',
    serviceUrl: 'https://onedrive.live.com',
    defaultAmount: 1.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.CLOUD_STORAGE,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Box Personal',
    description: 'Secure cloud storage and file sharing for individuals',
    iconUrl: 'https://logo.clearbit.com/box.com',
    serviceUrl: 'https://box.com',
    defaultAmount: 10.0,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.CLOUD_STORAGE,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'pCloud Premium',
    description: 'Lifetime or annual cloud storage with end-to-end encryption',
    iconUrl: 'https://logo.clearbit.com/pcloud.com',
    serviceUrl: 'https://pcloud.com',
    defaultAmount: 4.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.CLOUD_STORAGE,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },

  // ── PRODUCTIVITY (6) ─────────────────────────────────────────────────────────
  {
    name: 'Microsoft 365',
    description:
      'Office apps, cloud storage and productivity tools from Microsoft',
    iconUrl: 'https://logo.clearbit.com/microsoft.com',
    serviceUrl: 'https://microsoft.com/microsoft-365',
    defaultAmount: 9.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.PRODUCTIVITY,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Notion',
    description: 'All-in-one workspace for notes, tasks, wikis and databases',
    iconUrl: 'https://logo.clearbit.com/notion.so',
    serviceUrl: 'https://notion.so',
    defaultAmount: 10.0,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.PRODUCTIVITY,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Evernote Personal',
    description: 'Note-taking and organisation app for individuals',
    iconUrl: 'https://logo.clearbit.com/evernote.com',
    serviceUrl: 'https://evernote.com',
    defaultAmount: 10.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.PRODUCTIVITY,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Todoist Pro',
    description:
      'Task manager and to-do list app with project management features',
    iconUrl: 'https://logo.clearbit.com/todoist.com',
    serviceUrl: 'https://todoist.com',
    defaultAmount: 4.0,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.PRODUCTIVITY,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Grammarly Premium',
    description: 'AI-powered writing assistant for grammar, clarity and style',
    iconUrl: 'https://logo.clearbit.com/grammarly.com',
    serviceUrl: 'https://grammarly.com',
    defaultAmount: 12.0,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.PRODUCTIVITY,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Slack Pro',
    description: 'Team messaging and collaboration platform',
    iconUrl: 'https://logo.clearbit.com/slack.com',
    serviceUrl: 'https://slack.com',
    defaultAmount: 7.25,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.PRODUCTIVITY,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },

  // ── NEWS & MEDIA (6) ─────────────────────────────────────────────────────────
  {
    name: 'The New York Times',
    description: 'Digital access to NY Times news, cooking and games',
    iconUrl: 'https://logo.clearbit.com/nytimes.com',
    serviceUrl: 'https://nytimes.com',
    defaultAmount: 17.0,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.NEWS_MEDIA,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'The Washington Post',
    description: 'Digital subscription to The Washington Post',
    iconUrl: 'https://logo.clearbit.com/washingtonpost.com',
    serviceUrl: 'https://washingtonpost.com',
    defaultAmount: 9.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.NEWS_MEDIA,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'The Wall Street Journal',
    description: 'Business and financial news from Dow Jones',
    iconUrl: 'https://logo.clearbit.com/wsj.com',
    serviceUrl: 'https://wsj.com',
    defaultAmount: 24.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.NEWS_MEDIA,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'The Economist',
    description: 'Global news and analysis magazine with digital access',
    iconUrl: 'https://logo.clearbit.com/economist.com',
    serviceUrl: 'https://economist.com',
    defaultAmount: 22.0,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.NEWS_MEDIA,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Medium',
    description: 'Online publishing platform for articles and stories',
    iconUrl: 'https://logo.clearbit.com/medium.com',
    serviceUrl: 'https://medium.com',
    defaultAmount: 5.0,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.NEWS_MEDIA,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Substack',
    description: 'Newsletter subscription platform for independent writers',
    iconUrl: 'https://logo.clearbit.com/substack.com',
    serviceUrl: 'https://substack.com',
    defaultAmount: 5.0,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.NEWS_MEDIA,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },

  // ── FITNESS & HEALTH (6) ─────────────────────────────────────────────────────
  {
    name: 'Peloton',
    description: 'Fitness classes and connected equipment subscription',
    iconUrl: 'https://logo.clearbit.com/onepeloton.com',
    serviceUrl: 'https://onepeloton.com',
    defaultAmount: 44.0,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.FITNESS_HEALTH,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Calm',
    description: 'Meditation, sleep and relaxation app',
    iconUrl: 'https://logo.clearbit.com/calm.com',
    serviceUrl: 'https://calm.com',
    defaultAmount: 69.99,
    defaultFrequency: BillingFrequency.ANNUAL,
    category: TemplateCategory.FITNESS_HEALTH,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Headspace',
    description: 'Mindfulness and meditation app for stress and sleep',
    iconUrl: 'https://logo.clearbit.com/headspace.com',
    serviceUrl: 'https://headspace.com',
    defaultAmount: 12.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.FITNESS_HEALTH,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'MyFitnessPal Premium',
    description: 'Calorie tracking, nutrition diary and fitness planning app',
    iconUrl: 'https://logo.clearbit.com/myfitnesspal.com',
    serviceUrl: 'https://myfitnesspal.com',
    defaultAmount: 9.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.FITNESS_HEALTH,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Strava Summit',
    description: 'GPS running and cycling tracking with advanced analytics',
    iconUrl: 'https://logo.clearbit.com/strava.com',
    serviceUrl: 'https://strava.com',
    defaultAmount: 7.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.FITNESS_HEALTH,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Noom',
    description: 'Weight loss and healthy lifestyle coaching app',
    iconUrl: 'https://logo.clearbit.com/noom.com',
    serviceUrl: 'https://noom.com',
    defaultAmount: 59.0,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.FITNESS_HEALTH,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },

  // ── EDUCATION (6) ────────────────────────────────────────────────────────────
  {
    name: 'Duolingo Plus',
    description: 'Ad-free language learning with offline access',
    iconUrl: 'https://logo.clearbit.com/duolingo.com',
    serviceUrl: 'https://duolingo.com',
    defaultAmount: 6.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.EDUCATION,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Coursera Plus',
    description: 'Unlimited access to 7,000+ courses and certificates',
    iconUrl: 'https://logo.clearbit.com/coursera.org',
    serviceUrl: 'https://coursera.org',
    defaultAmount: 59.0,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.EDUCATION,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'LinkedIn Learning',
    description: 'Online learning platform with business and tech courses',
    iconUrl: 'https://logo.clearbit.com/linkedin.com',
    serviceUrl: 'https://linkedin.com/learning',
    defaultAmount: 29.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.EDUCATION,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Udemy Business',
    description: "Access to Udemy's top courses for professional development",
    iconUrl: 'https://logo.clearbit.com/udemy.com',
    serviceUrl: 'https://udemy.com',
    defaultAmount: 30.0,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.EDUCATION,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'MasterClass',
    description: 'Online classes taught by world-class experts',
    iconUrl: 'https://logo.clearbit.com/masterclass.com',
    serviceUrl: 'https://masterclass.com',
    defaultAmount: 10.0,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.EDUCATION,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Brilliant',
    description:
      'Interactive STEM learning with math, science and computer science',
    iconUrl: 'https://logo.clearbit.com/brilliant.org',
    serviceUrl: 'https://brilliant.org',
    defaultAmount: 24.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.EDUCATION,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },

  // ── FOOD DELIVERY (6) ────────────────────────────────────────────────────────
  {
    name: 'DoorDash DashPass',
    description: 'Unlimited free delivery and reduced service fees on DoorDash',
    iconUrl: 'https://logo.clearbit.com/doordash.com',
    serviceUrl: 'https://doordash.com/dashpass',
    defaultAmount: 9.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.FOOD_DELIVERY,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Uber One',
    description:
      'Membership for free delivery and discounts on Uber Eats and rides',
    iconUrl: 'https://logo.clearbit.com/uber.com',
    serviceUrl: 'https://uber.com/uber-one',
    defaultAmount: 9.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.FOOD_DELIVERY,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Grubhub+',
    description: 'Unlimited free delivery and exclusive perks on Grubhub',
    iconUrl: 'https://logo.clearbit.com/grubhub.com',
    serviceUrl: 'https://grubhub.com/plus',
    defaultAmount: 9.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.FOOD_DELIVERY,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Instacart+',
    description: 'Unlimited free grocery delivery from local stores',
    iconUrl: 'https://logo.clearbit.com/instacart.com',
    serviceUrl: 'https://instacart.com/plus',
    defaultAmount: 9.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.FOOD_DELIVERY,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'HelloFresh',
    description:
      'Weekly meal kit subscription with fresh ingredients and recipes',
    iconUrl: 'https://logo.clearbit.com/hellofresh.com',
    serviceUrl: 'https://hellofresh.com',
    defaultAmount: 79.0,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.FOOD_DELIVERY,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Factor Meals',
    description: 'Fresh, chef-prepared meals delivered weekly to your door',
    iconUrl: 'https://logo.clearbit.com/factor75.com',
    serviceUrl: 'https://factor75.com',
    defaultAmount: 120.0,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.FOOD_DELIVERY,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },

  // ── SECURITY & VPN (6) ───────────────────────────────────────────────────────
  {
    name: 'NordVPN',
    description: 'Fast and secure VPN with servers in 60+ countries',
    iconUrl: 'https://logo.clearbit.com/nordvpn.com',
    serviceUrl: 'https://nordvpn.com',
    defaultAmount: 11.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.SECURITY_VPN,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'ExpressVPN',
    description: 'High-speed VPN with servers in 94 countries',
    iconUrl: 'https://logo.clearbit.com/expressvpn.com',
    serviceUrl: 'https://expressvpn.com',
    defaultAmount: 12.95,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.SECURITY_VPN,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Surfshark',
    description: 'Budget VPN with unlimited simultaneous connections',
    iconUrl: 'https://logo.clearbit.com/surfshark.com',
    serviceUrl: 'https://surfshark.com',
    defaultAmount: 3.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.SECURITY_VPN,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: '1Password',
    description: 'Password manager and digital vault for individuals',
    iconUrl: 'https://logo.clearbit.com/1password.com',
    serviceUrl: 'https://1password.com',
    defaultAmount: 2.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.SECURITY_VPN,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'LastPass Premium',
    description: 'Password manager with secure vault and dark web monitoring',
    iconUrl: 'https://logo.clearbit.com/lastpass.com',
    serviceUrl: 'https://lastpass.com',
    defaultAmount: 3.0,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.SECURITY_VPN,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Dashlane Premium',
    description: 'Password manager with VPN and identity monitoring',
    iconUrl: 'https://logo.clearbit.com/dashlane.com',
    serviceUrl: 'https://dashlane.com',
    defaultAmount: 4.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.SECURITY_VPN,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },

  // ── OTHER (10) ───────────────────────────────────────────────────────────────
  {
    name: 'Amazon Prime',
    description: 'Free shipping, Prime Video, Prime Music and more from Amazon',
    iconUrl: 'https://logo.clearbit.com/amazon.com',
    serviceUrl: 'https://amazon.com/prime',
    defaultAmount: 14.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.OTHER,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Adobe Creative Cloud',
    description:
      'Suite of creative apps including Photoshop, Illustrator and Premiere',
    iconUrl: 'https://logo.clearbit.com/adobe.com',
    serviceUrl: 'https://adobe.com/creativecloud',
    defaultAmount: 54.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.OTHER,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'GitHub Copilot',
    description: 'AI coding assistant for developers in VS Code and JetBrains',
    iconUrl: 'https://logo.clearbit.com/github.com',
    serviceUrl: 'https://github.com/features/copilot',
    defaultAmount: 10.0,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.OTHER,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'ChatGPT Plus',
    description:
      'Priority access to GPT-4 and advanced AI features from OpenAI',
    iconUrl: 'https://logo.clearbit.com/openai.com',
    serviceUrl: 'https://chat.openai.com',
    defaultAmount: 20.0,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.OTHER,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Figma Professional',
    description: 'Collaborative design tool for UI/UX designers',
    iconUrl: 'https://logo.clearbit.com/figma.com',
    serviceUrl: 'https://figma.com',
    defaultAmount: 12.0,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.OTHER,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Canva Pro',
    description: 'Graphic design platform with premium templates and assets',
    iconUrl: 'https://logo.clearbit.com/canva.com',
    serviceUrl: 'https://canva.com',
    defaultAmount: 12.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.OTHER,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Zoom Pro',
    description:
      'Video conferencing with up to 100 participants and 30-hour meetings',
    iconUrl: 'https://logo.clearbit.com/zoom.us',
    serviceUrl: 'https://zoom.us',
    defaultAmount: 14.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.OTHER,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Shopify Basic',
    description: 'E-commerce platform for small businesses and online stores',
    iconUrl: 'https://logo.clearbit.com/shopify.com',
    serviceUrl: 'https://shopify.com',
    defaultAmount: 29.0,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.OTHER,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Mailchimp Essentials',
    description: 'Email marketing platform for businesses and creators',
    iconUrl: 'https://logo.clearbit.com/mailchimp.com',
    serviceUrl: 'https://mailchimp.com',
    defaultAmount: 13.0,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.OTHER,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
  {
    name: 'Twitch Turbo',
    description: 'Ad-free viewing and exclusive perks on Twitch',
    iconUrl: 'https://logo.clearbit.com/twitch.tv',
    serviceUrl: 'https://twitch.tv/turbo',
    defaultAmount: 8.99,
    defaultFrequency: BillingFrequency.MONTHLY,
    category: TemplateCategory.OTHER,
    ownership: TemplateOwnership.GLOBAL,
    userId: null,
  },
];
