export enum TemplateCategory {
  STREAMING = 'STREAMING',
  MUSIC = 'MUSIC',
  GAMING = 'GAMING',
  CLOUD_STORAGE = 'CLOUD_STORAGE',
  PRODUCTIVITY = 'PRODUCTIVITY',
  NEWS_MEDIA = 'NEWS_MEDIA',
  FITNESS_HEALTH = 'FITNESS_HEALTH',
  EDUCATION = 'EDUCATION',
  FOOD_DELIVERY = 'FOOD_DELIVERY',
  SECURITY_VPN = 'SECURITY_VPN',
  OTHER = 'OTHER',
}
